
 Rank = 8 started! Wed Jun 30 11:18:15 2021

 Rank = 5 started! Wed Jun 30 11:18:15 2021

 Rank = 12 started! Wed Jun 30 11:18:15 2021

 Rank = 0 started! Wed Jun 30 11:18:15 2021

 Rank = 13 started! Wed Jun 30 11:18:15 2021

 Rank = 16 started! Wed Jun 30 11:18:15 2021

 Rank = 19 started! Wed Jun 30 11:18:15 2021

 Rank = 4 started! Wed Jun 30 11:18:15 2021

 Rank = 6 started! Wed Jun 30 11:18:15 2021

 Rank = 2 started! Wed Jun 30 11:18:15 2021

 Rank = 17 started! Wed Jun 30 11:18:15 2021

 Rank = 1 started! Wed Jun 30 11:18:15 2021

 Rank = 10 started! Wed Jun 30 11:18:15 2021

 Rank = 22 started! Wed Jun 30 11:18:15 2021

 Rank = 11 started! Wed Jun 30 11:18:15 2021

 Rank = 3 started! Wed Jun 30 11:18:15 2021

 Rank = 7 started! Wed Jun 30 11:18:15 2021

 Rank = 14 started! Wed Jun 30 11:18:15 2021

 Rank = 21 started! Wed Jun 30 11:18:15 2021

 Rank = 23 started! Wed Jun 30 11:18:15 2021

 Rank = 20 started! Wed Jun 30 11:18:15 2021

 Rank = 9 started! Wed Jun 30 11:18:15 2021

 Rank = 15 started! Wed Jun 30 11:18:15 2021

 Rank = 18 started! Wed Jun 30 11:18:15 2021
num_files =  600
Finding the central part_IDs
Rank  18 No part within radii!
Rank  16 No part within radii!
Rank  17 No part within radii!
Rank : 0 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
Central_prt_IDs found!
0%
Rank : 5 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  5 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 2 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  2 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 4 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  4 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 17 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  17 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 18 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  18 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 11 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  11 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Rank : 14 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  14 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 12 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  12 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 6 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  6 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Rank : 8 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  8 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 23 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  23 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 7 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  7 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 16 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  16 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 22 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  22 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 20 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  20 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 15 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  15 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 13 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  13 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 19 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  19 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
Rank : 10 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  10 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Traceback (most recent call last):
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 111, in get_part_coord_parallel
    common_coords =  f['PartType'+str(PartType)]['Coordinates'][ind_common_set] + (1000*(f['PartType'+str(PartType)]['Velocities'][ind_common_set]/(Hz*(1+z)**0.5))*h)%boxsize
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/mqezlou/.conda/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 361, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
rank  0 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Rank  0 saving on file
Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 118, in get_part_coord_parallel
    with h5py.File('./PartType1/individual_clusters/'+str(cluster_ind)+'/prog_snap'+fn[61:-5]+'_rank'+str(rank)+'.hdf5','w') as fw:
TypeError: must be str, not list
Rank : 1 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  1 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Rank  1 saving on file
Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 118, in get_part_coord_parallel
    with h5py.File('./PartType1/individual_clusters/'+str(cluster_ind)+'/prog_snap'+fn[61:-5]+'_rank'+str(rank)+'.hdf5','w') as fw:
TypeError: must be str, not list
Rank : 9 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  9 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Rank  9 saving on file
Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 118, in get_part_coord_parallel
    with h5py.File('./PartType1/individual_clusters/'+str(cluster_ind)+'/prog_snap'+fn[61:-5]+'_rank'+str(rank)+'.hdf5','w') as fw:
TypeError: must be str, not list
Rank : 3 IDs_all_ranks [2606530495 2605896895 2606505695 ... 2441184895 2840378095 3577347715]
rank  3 fn  ['/lustre/scratch/mqezlou/TNG300-1/output/snapdir_030/snap_030.0.hdf5'] Wed Jun 30 11:18:18 2021
Rank  3 saving on file
Traceback (most recent call last):
  File "progenitor_parallel.py", line 64, in <module>
    progenitor_particles.get_part_coord_parallel(MPI=MPI, fnames_rank=fnames_rank, PartType=args.PartType, cluster_ind=args.cluster)
  File "/lustre/scratch/mqezlou/TNG300-1/postprocessing/progenitor/progenitor_particles.py", line 118, in get_part_coord_parallel
    with h5py.File('./PartType1/individual_clusters/'+str(cluster_ind)+'/prog_snap'+fn[61:-5]+'_rank'+str(rank)+'.hdf5','w') as fw:
TypeError: must be str, not list
srun: First task exited 60s ago
srun: step:7468121.0 task 1: running
srun: step:7468121.0 task 0: exited
srun: Terminating job step 7468121.0
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
[mpiexec@memex-c070] control_cb (pm/pmiserv/pmiserv_cb.c:208): assert (!closed) failed
[mpiexec@memex-c070] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@memex-c070] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:198): error waiting for event
[mpiexec@memex-c070] main (ui/mpich/mpiexec.c:340): process manager error waiting for completion
